#!/usr/bin/env python3
"""
Generate ocean tile with Korea cutout using PROPER geographic coordinates.

The key insight: Both the ocean tile and Korea polygons must be transformed
using the SAME coordinate system (DEM CRS -> mm) to ensure correct positioning.

This script:
1. Loads the v3-style ocean tile
2. Loads North and South Korea from Natural Earth (same source as ocean generation)
3. Transforms Korea polygons using the SAME DEM transform as the ocean tile
4. Cuts both Koreas from the ocean tile
5. Result: Proper geographic alignment between Korea and Japan
"""

import json
import os
import sys

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import rasterio
import trimesh
from rasterio.mask import mask as rasterio_mask
from shapely.affinity import affine_transform
from shapely.geometry import Polygon
from shapely.ops import unary_union
from shapely.validation import make_valid

# Import constants from v3 script
sys.path.insert(0, os.path.dirname(__file__))
from generate_ocean_tile_v3 import (
    GLOBAL_XY_SCALE,
    MIRROR_X,
    VECTOR_SIMPLIFY_DEGREES,
)

# v3 now overrides XY_MM_PER_PIXEL to 0.50 for Eurasia 2km DEM
# This matches the GOLD STLs (generated by make_eurasia_all.py)
XY_MM_PER_PIXEL = 0.50


def get_simplified_geometry(gdf, country_name, simplify_deg=VECTOR_SIMPLIFY_DEGREES):
    """Get country geometry with same simplification as STL generation."""
    row = gdf[gdf["ADMIN"] == country_name]
    if len(row) == 0:
        return None
    geom = row.iloc[0].geometry
    if simplify_deg > 0:
        geom = geom.simplify(simplify_deg, preserve_topology=True)
    if not geom.is_valid:
        geom = make_valid(geom)
    return geom


def create_ocean_with_proper_korea_cutout(
    dem_path, ne_path, ocean_stl_path, output_dir
):
    """
    Create ocean tile with Korea cutout using proper geographic coordinates.
    """
    print("=" * 60)
    print("Ocean tile with geographically-correct Korea cutout")
    print("=" * 60)

    # Load ocean tile
    print("\nLoading ocean tile...")
    ocean = trimesh.load(ocean_stl_path)
    ob = ocean.bounds
    print(
        f"  Ocean bounds: X=[{ob[0][0]:.1f}, {ob[1][0]:.1f}], Y=[{ob[0][1]:.1f}, {ob[1][1]:.1f}]"
    )

    # Load ocean tile metadata to get the DEM clip origin
    metadata_path = ocean_stl_path.replace(".stl", "_metadata.json")
    if not os.path.exists(metadata_path):
        print(f"ERROR: Missing metadata file: {metadata_path}")
        return None

    with open(metadata_path) as f:
        ocean_meta = json.load(f)

    dem_origin_x = ocean_meta["dem_clip_origin_crs"]["x"]
    dem_origin_y = ocean_meta["dem_clip_origin_crs"]["y"]
    print(f"  DEM clip origin: ({dem_origin_x:.1f}, {dem_origin_y:.1f})")

    # Load Natural Earth
    print("\nLoading Natural Earth...")
    gdf = gpd.read_file(ne_path)

    # Get Korea geometries (both North and South)
    sk_geom = get_simplified_geometry(gdf, "South Korea")
    nk_geom = get_simplified_geometry(gdf, "North Korea")

    if sk_geom is None or nk_geom is None:
        print("ERROR: Could not load Korea geometries")
        return None

    # Combine both Koreas
    korea_combined = unary_union([sk_geom, nk_geom])
    print(f"  Combined Korea bounds (WGS84): {korea_combined.bounds}")

    # Load DEM to get the transform
    print("\nLoading DEM for coordinate transform...")
    dem_src = rasterio.open(dem_path)
    dem_crs = dem_src.crs

    # Reproject Korea to DEM CRS
    korea_crs = gpd.GeoSeries([korea_combined], crs="EPSG:4326").to_crs(dem_crs).iloc[0]
    print(f"  Korea bounds (DEM CRS): {korea_crs.bounds}")

    # Now we need to transform Korea from DEM CRS to the ocean tile's mm coordinates
    # The ocean tile was clipped from a specific region of the DEM
    # We need to find that clip region and apply the same transform

    # The ocean tile's DEM clip origin is stored in metadata
    # We need to recompute the transform used during ocean tile generation
    #
    # From v3 script:
    #   a = XY_MM_PER_PIXEL / pixel_width
    #   e = XY_MM_PER_PIXEL / pixel_height
    #   xoff = -origin_x * XY_MM_PER_PIXEL / pixel_width
    #   yoff = -origin_y * XY_MM_PER_PIXEL / pixel_height

    # But we don't have pixel_width from just the STL...
    # Let's use the DEM's pixel size and the clip origin

    # Get DEM pixel size
    pixel_width = dem_src.transform.a  # meters per pixel in X
    pixel_height = dem_src.transform.e  # meters per pixel in Y (negative)
    print(f"  DEM pixel size: {pixel_width:.1f}m x {abs(pixel_height):.1f}m")

    # The transform from DEM CRS to mm coordinates
    # mm = (crs - origin) / pixel_size * XY_MM_PER_PIXEL
    a = XY_MM_PER_PIXEL / pixel_width
    b = 0
    d = 0
    e = XY_MM_PER_PIXEL / pixel_height  # This handles Y flip
    xoff = -dem_origin_x * XY_MM_PER_PIXEL / pixel_width
    yoff = -dem_origin_y * XY_MM_PER_PIXEL / pixel_height

    # Transform Korea polygon to mm coordinates
    korea_mm = affine_transform(korea_crs, [a, b, d, e, xoff, yoff])

    # Apply the same GLOBAL_XY_SCALE and MIRROR_X as the ocean tile
    if GLOBAL_XY_SCALE != 1.0:
        korea_mm = affine_transform(
            korea_mm, [GLOBAL_XY_SCALE, 0, 0, GLOBAL_XY_SCALE, 0, 0]
        )

    if MIRROR_X:
        korea_mm = affine_transform(korea_mm, [-1, 0, 0, 1, 0, 0])
        # DO NOT shift Korea by its own max X. The ocean tile's coordinate
        # system has x=0 at the westernmost pixel column of its DEM clip.
        # Korea must stay in that same coordinate system - no independent shift.

    kmb = korea_mm.bounds
    print(
        f"  Korea bounds (mm, transformed): X=[{kmb[0]:.1f}, {kmb[2]:.1f}], Y=[{kmb[1]:.1f}, {kmb[3]:.1f}]"
    )

    # Check overlap with ocean tile
    print("\n  Checking alignment:")
    print(f"    Ocean X: [{ob[0][0]:.1f}, {ob[1][0]:.1f}]")
    print(f"    Korea X: [{kmb[0]:.1f}, {kmb[2]:.1f}]")
    print(f"    Ocean Y: [{ob[0][1]:.1f}, {ob[1][1]:.1f}]")
    print(f"    Korea Y: [{kmb[1]:.1f}, {kmb[3]:.1f}]")

    # Add buffer to Korea polygon to sever thin mesh connections
    KOREA_BUFFER_MM = 0.5
    korea_mm_buffered = korea_mm.buffer(KOREA_BUFFER_MM)
    print(f"\n  Applied {KOREA_BUFFER_MM}mm buffer to Korea cutter")

    # If MultiPolygon, merge into single polygon
    if korea_mm_buffered.geom_type == "MultiPolygon":
        # Buffer and unbuffer to merge nearby polygons
        korea_mm_buffered = korea_mm_buffered.buffer(0.1).buffer(-0.1)
        if korea_mm_buffered.geom_type == "MultiPolygon":
            # Take the largest polygon
            korea_mm_buffered = max(korea_mm_buffered.geoms, key=lambda p: p.area)
        print(f"  Merged MultiPolygon to single Polygon")

    # Create cutter mesh
    print("\nCreating Korea cutter mesh...")
    z_min = ocean.bounds[0][2] - 1
    z_max = ocean.bounds[1][2] + 1
    height = z_max - z_min + 2

    korea_cutter = trimesh.creation.extrude_polygon(korea_mm_buffered, height=height)
    korea_cutter.apply_translation([0, 0, z_min - 0.5])
    print(f"  Korea cutter: {len(korea_cutter.faces)} faces")

    # Apply Korea cutout
    print("\nPerforming boolean subtraction...")
    try:
        ocean_cut = ocean.difference(korea_cutter, engine="manifold")
        print(f"  After Korea cut: {len(ocean_cut.faces)} faces")
    except Exception as e:
        print(f"  ERROR: Korea cut failed: {e}")
        return None

    # Remove disconnected pieces
    print("\nRemoving disconnected pieces...")
    components = ocean_cut.split(only_watertight=False)
    print(f"  Found {len(components)} connected components")

    if len(components) > 1:
        component_sizes = [(i, len(c.faces)) for i, c in enumerate(components)]
        component_sizes.sort(key=lambda x: x[1], reverse=True)

        print("  Component sizes:")
        for i, (idx, size) in enumerate(component_sizes[:10]):
            cb = components[idx].bounds
            print(
                f"    {i + 1}. {size:,} faces, X=[{cb[0][0]:.1f}, {cb[1][0]:.1f}], Y=[{cb[0][1]:.1f}, {cb[1][1]:.1f}]"
            )

        largest_idx = component_sizes[0][0]
        ocean_final = components[largest_idx]
        print(f"  Keeping largest: {len(ocean_final.faces):,} faces")
    else:
        ocean_final = ocean_cut
        print("  Only one component, keeping all")

    # Visualize
    print("\nGenerating visualization...")
    fig, axes = plt.subplots(1, 3, figsize=(18, 8))

    # Original ocean
    ax1 = axes[0]
    ov = ocean.vertices[ocean.vertices[:, 2] < 0.5]
    ax1.scatter(ov[:, 0], ov[:, 1], s=0.3, alpha=0.3, c="blue")
    ax1.set_title("Original Ocean")
    ax1.set_aspect("equal")
    ax1.grid(True, alpha=0.3)

    # Korea cutter position
    ax2 = axes[1]
    ax2.scatter(ov[:, 0], ov[:, 1], s=0.3, alpha=0.2, c="blue", label="Ocean")
    if korea_mm_buffered.geom_type == "Polygon":
        x, y = korea_mm_buffered.exterior.xy
        ax2.plot(x, y, "r-", linewidth=2, label="Korea cutter")
    elif korea_mm_buffered.geom_type == "MultiPolygon":
        for poly in korea_mm_buffered.geoms:
            x, y = poly.exterior.xy
            ax2.plot(x, y, "r-", linewidth=2)
    ax2.set_title("Korea cutter position")
    ax2.legend()
    ax2.set_aspect("equal")
    ax2.grid(True, alpha=0.3)

    # Final result
    ax3 = axes[2]
    fv = ocean_final.vertices[ocean_final.vertices[:, 2] < 0.5]
    ax3.scatter(fv[:, 0], fv[:, 1], s=0.3, alpha=0.3, c="blue")
    ax3.set_title("Final (largest component)")
    ax3.set_aspect("equal")
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f"{output_dir}/ocean_korea_cutout_v2.png", dpi=150)
    print(f"Saved: {output_dir}/ocean_korea_cutout_v2.png")
    plt.close()

    # Save results
    output_path = f"{output_dir}/Japan_ocean_with_korea_cutout_v2.stl"
    ocean_final.export(output_path)
    print(f"Saved: {output_path}")

    # Report final dimensions
    fb = ocean_final.bounds
    print(f"\nFinal ocean tile:")
    print(f"  X: {fb[0][0]:.1f} to {fb[1][0]:.1f} (width: {fb[1][0] - fb[0][0]:.1f})")
    print(f"  Y: {fb[0][1]:.1f} to {fb[1][1]:.1f} (height: {fb[1][1] - fb[0][1]:.1f})")
    print(f"  Faces: {len(ocean_final.faces):,}")

    dem_src.close()
    return ocean_final


if __name__ == "__main__":
    create_ocean_with_proper_korea_cutout(
        dem_path="eurasia_2km_smooth_aea.tif",
        ne_path="data/ne/ne_10m_admin_0_countries.shp",
        ocean_stl_path="STLs_Ocean_v3_fixed/Japan_ocean_tile.stl",
        output_dir="STLs_Ocean_v3_fixed",
    )
